In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

sns.set_style('whitegrid')
sns.set_context('notebook')

In [3]:
customers = pd.read_csv('../data/raw.csv')

In [4]:
customers.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
"Percentage of customers churned: %{:.2f}".format(len(customers[customers['Churn']=='Yes'])/len(customers)*100)

'Percentage of customers churned: %26.54'

In [7]:
# Change object column to float
customers['TotalCharges'] = pd.to_numeric(customers.TotalCharges, errors='coerce')
# Check
customers.MonthlyCharges.describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [8]:
# Looks like we have a lot of Yes/No and other categorical columns. Check unique values:
uniques = {col:customers[col].unique() if len(customers[col].unique())<=10 else '>10 unique values' \
           for col in customers.columns}
uniques_df = pd.DataFrame.from_dict(uniques, orient='index', columns=['unique values'])
uniques_df

                                                      unique values
customerID                                        >10 unique values
gender                                               [Female, Male]
SeniorCitizen                                                [0, 1]
Partner                                                   [Yes, No]
Dependents                                                [No, Yes]
tenure                                            >10 unique values
PhoneService                                              [No, Yes]
MultipleLines                           [No phone service, No, Yes]
InternetService                              [DSL, Fiber optic, No]
OnlineSecurity                       [No, Yes, No internet service]
OnlineBackup                         [Yes, No, No internet service]
DeviceProtection                     [No, Yes, No internet service]
TechSupport                          [No, Yes, No internet service]
StreamingTV                          [No, Yes, No internet service]
StreamingMovies                      [No, Yes, No internet service]
Contract                       [Month-to-month, One year, Two year]
PaperlessBilling                                          [Yes, No]
PaymentMethod     [Electronic check, Mailed check, Bank transfer...
MonthlyCharges                                    >10 unique values
TotalCharges                                      >10 unique values
Churn                                                     [No, Yes]

In [9]:
# PaymentMethod values are cut off in the above view. Closer look:
customers.PaymentMethod.unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [10]:
customers[customers.duplicated()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [11]:
customers.customerID.is_unique

True